version: 1.9.7.{build}

image: Visual Studio 2017

pull_requests:

  do_not_increment_build_number: true

branches:

  only:

  - master

skip_tags: true

configuration:

- Debug

- Release

platform: Any CPU

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

cache: packages -> **\packages.config

before_build:

- cmd: >-

    git submodule update --init --recursive



    nuget restore

build:

  verbosity: minimal
